formatter: "markdown"

version: ""

header-from: header.md
footer-from: footer.md

sections:
  hide: []
  show: []

content: |-
  {{ .Header }}


  {{ .Requirements }}
  {{ .Providers }}
  {{ .Inputs }}
  {{ .Outputs }}

  ## Examples
  ### AWS Example

  ```hcl
  {{ include "examples/simple/main.tf" }}
  ```

  ### K8s Example

  ```hcl
  {{ include "examples/k8s/main.tf" }}
  ```

  {{ .Footer }}

output:
  file: "README.md"
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  required: true
  sensitive: true
